<!DOCTYPE html>
<html>
    <head>
        <title>Homepage</title>
        <link rel="stylesheet" href="Good-Vibes[Homepage].css">
    </head>
    <body>
        
        <header>
            <nav class="navbar">
                <ul class="navlist">
                    <li><a href="#About us">About us</a></li>
                    <li><a href="mailto:good.vibes.help2022@gmail.com">Contact</a></li>
                    <div><h1>ğŸŒ´ğ“–ğ“ğ“ğ““ ğ“¥ğ“˜ğ“‘ğ“”ğ“¢ğŸŒ´</h1></div>
                </ul>
            </nav>
            
            <nav class="Logo">
            <img src="http://cdn.shopify.com/s/files/1/0567/8229/1140/products/good_vibes_neon_sign_melbourne_2_1200x.jpg?v=1632005338" width="75px">
            </nav>
        </header>
        <br>
        
        <nav class="Ãœberschrift">
            <h2>ğŸŒ´ğ“–ğ“ğ“ğ““ ğ“¥ğ“˜ğ“‘ğ“”ğ“¢ğŸŒ´</h2>
        </nav>
        <nav class="Info">
            <p></p>
        </nav>
        <br>
        <div class="cssSlider">
 
            <!-- die inputs um den Slider zu Steuern -->
            <input type="radio" name="slider" id="slide01" checked="checked">
            <input type="radio" name="slider" id="slide02">
            <input type="radio" name="slider" id="slide03">
            <input type="radio" name="slider" id="slide04">
         
            <!-- die einzelnen Slides, hier als Liste angelegt -->
            <ul class="sliderElements">
                <li>
                    <figure>
                        <img src="http://cdn.shopify.com/s/files/1/0567/8229/1140/products/good_vibes_neon_sign_melbourne_2_1200x.jpg?v=1632005338" alt="" height="400" width="1200">
                        <figcaption>
                            Good vibes is a server to chill.</figcaption>
                    </figure>
                </li>
                
                <li>
                    <figure>
                        <img src="https://static1.thegamerimages.com/wordpress/wp-content/uploads/2019/08/discord-go-live-promo.jpg?q=50&fit=contain&w=767&h=404&dpr=1.5" alt="" height="400px" width="1200px">
                        <figcaption>You can stream with your friends</figcaption>
                    </figure>
                </li>
                <li>
                    <figure>
                        <img src="https://i.ytimg.com/vi/xnYh_umUuaQ/maxresdefault.jpg" alt="" height="400" width="1200px">
                        <figcaption>Watch videos with your friends</figcaption>
                    </figure>
                </li>
                <li>
                    <figure>
                        <img src="https://scentculture.news/wp-content/uploads/2022/01/discord-memes-w2EmY-2.jpg" alt="" height="400" width="1200">
                        <figcaption>The best memes are always here for you too</figcaption>
                    </figure>
                </li>
            </ul>
         
            <!-- Eine Steuerung -->
            <ul class="sliderControls">
                <li><label for="slide01">1</label></li>
                <li><label for="slide02">2</label></li>
                <li><label for="slide03">3</label></li>
                <li><label for="slide04">4</label></li>
            </ul>
        </div>

        <br><br>
        
        <div class="DiscordLogo"><img src="https://www.designtagebuch.de/wp-content/uploads/mediathek//2021/05/discord-logo-1100x825.jpg" alt="" height="50px" width="70px"></div>
        <button class="JoinDiscord"  type="Button" onclick="window.location.href ='https://discord.gg/bqKTEF6N'"  ><div class="DiscordText">Join our Discord</div></button>
        <br>
        <br><br>
        <nav class="Info2">
        <p>ğŸŒ´ğ“–ğ“ğ“ğ““ ğ“¥ğ“˜ğ“‘ğ“”ğ“¢ğŸŒ´<br>
            <h5>Is there a place for his friends and for himself.</h5>
            <h5>You have the following options:</h5>
            <h3>â•‘ğŸ«Netflix&Chillâ•‘</h3>
        <h8>You can spend a relaxing evening with your friends watching youtube or netflix</h8>
        <br><br>
        <h3>â•‘ğŸ”ŠVoice Talkâ•‘</h3>
        <h8>We have our own voice chat for you and your friends</h8>
        <br><br>
        <h3>â•‘ğŸ”´STREAMING Channelsâ•‘</h3>
        <h8>You can open a stream for your friends and yourself</h8>
        <br><br>
        <h3>â•‘ğŸ¶Musicâ•‘</h3>
        <h8>Listening to music will not be a problem for you</h8>
        <br><br>
        <h3>â•‘ğŸ˜œMemesâ•‘</h3>
        <h8>The best memes won't have one either</h8>
        </p>
        </nav>
        <section id="About us">
        <footer>
            <hr>
            <div class="Aboutus2">
                <h4>About us</h4>
            </div>
            <nav class="Aboutus">
            <p>Server Owner <br> <div class="Owner">Pasqualle & Ginger alle</div> </p>
            </nav>

            <div class="YTLogo"><img src="https://www.baranek-renger.de/wp-content/uploads/1000px_youtube.png" alt="" height="50px" width="60px"></div>
        <button class="JoinYT"  type="Button" onclick="window.location.href ='https://www.youtube.com/channel/UCCTVgaz2g6LHIgJGLHmSVZA'"  ><div class="YTText">Join my YouTube</div></button>
        </footer>
       </section>
    </body>
</html>
body {
    background: white;
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.06);
    color: black;
    font-family: "Helvetica Neue", Arial, Helvetica, sans-serif;
    font-size: 16px;
    line-height: 1.5;
    margin: 0 auto;
    max-width: 800px;
    padding: 0em 0em 2em;
}


.navbar{
background-color: black;
height: 60px;
}

.navlist{
float: right;
}

.navlist li{
display: inline-block;
}

.navlist li a{
color: white;
margin: 0 10px;
text-decoration: none;
}

.navlist li a:hover{
color: lightgray;
text-decoration: underline;
}

.navlist div{
    color: white;
    position: absolute;
    left: 27%;
    top: -1%;
}

.Ãœberschrift{
    position: relative;
    left: 3.5%;
    color: black;
}

.Info{
    color: lightskyblue;
    position: absolute;
    top: 19%;
}

.Bild1{
    position: absolute;
    width: 950px;
    height: 580px;
    left: auto;
}

.Logo{
    position: absolute;
    top: 1%;
    left: 22%;
}

.Info2{
    position: relative;
    left: 3.5%;
    color: black;
}

.Aboutus{
    color: gray;
    position: relative;
    top: 110%;
    left: 3.5%;
    font-size: smaller;
}

.Aboutus2{
    position: relative;
    left: 3.5%;
    color: black;
}

body{
    box-shadow: 6px -19px 110000px lightgray;
}

.Owner{
    color: black;
}

.DiscordLogo{
    position: absolute;
    left: 22%;
    top: 120%;
}

.JoinDiscord{
    display: inline-flex;
    background: rgb(52, 115, 218);
    padding: 0;
    border: none;
    outline: none;
    border-radius: 5px;
    overflow: hidden;
    height: 7.5%;
    width: 10%;
    position: absolute;
    left: 27%;
    top: 120%;
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
}

.DiscordText{
position: absolute;
top: 30%;
color: white;
left: 6%;
font-size: 125%;
}

.YTLogo{
    position: absolute;
    left: 58%;
    top: 248%;
}

.JoinYT{
    display: inline-flex;
    background: rgb(255, 30, 0);
    padding: 0;
    border: none;
    outline: none;
    border-radius: 5px;
    overflow: hidden;
    height: 7.64%;
    width: 10%;
    position: absolute;
    left: 62%;
    top: 247.9%;
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
}

.YTText{
    position: absolute;
    top: 30%;
    color: white;
    left: 6%;
    font-size: 125%;
    }


.sliderElements,
.sliderElements figure,
.sliderControls {
    margin: 0;
}
 
.sliderElements:after {
    content: ".";
    display: block;
    height: .1px;
    clear: both;
    visibility: hidden;
    font-size: 0;
    overflow: hidden;
}
 
.cssSlider {
    overflow-x: hidden;
}
 
.sliderElements {
    list-style: none;
    position: relative;
    left: 0;
    width: 400%;
    margin-bottom: .8em;
    padding: 0;
    -webkit-transition: left .8s ease-in-out;
    -moz-transition: left .8s ease-in-out;
    -o-transition: left .8s ease-in-out;
    transition: left .8s ease-in-out;
}
 
.sliderElements > li {
    float: left;
    width: 25%;
    position: relative;
}
 
#slide02:checked ~ .sliderElements {
    left: -100%;
}
 
#slide03:checked ~ .sliderElements {
    left: -200%;
}
 
#slide04:checked ~ .sliderElements {
    left: -300%;
}
 
/* Bildunterschrift auf dem Bild positionieren */
.sliderElements figcaption {
    display: block;
    color: #fff;
    position: absolute;
    left: 0;
    bottom: 1em;
    padding: .4em;
    background: rgba(0,0,0,.5);
}
 
/* Bilder responsive */
.sliderElements img {
    width: 100%;
    height: 500px;
}
 
 
/* inputs aus dem Blickfeld schieben */
.cssSlider input {
    position: absolute;
    left: -99999px;
}
 
/* mittige Ausrichtung der Controls - funktioniert im Zusammenspiel mit inline-block */
.sliderControls {
    text-align: center;
}
 
/* Controls nebeneinander bringen */
.sliderControls li {
    display: inline-block;
}
 
/* Controls auf einheitliche MaÃŸe bringen und die Ecken abrunden */
.sliderControls label {
    width: 20px;
    height: 20px;
    line-height: 20px;
    text-align: center;
    border-radius: 50%;
    display: block;
    cursor: pointer;
    background: #68B022;
    color: #68B022;
}
 
/* Attributselektor und indirekter Nachfahrkombinator zum ansteuern der labels */
.sliderControls label:hover,
#slide01:checked ~ .sliderControls label[for="slide01"],
#slide02:checked ~ .sliderControls label[for="slide02"],
#slide03:checked ~ .sliderControls label[for="slide03"],
#slide04:checked ~ .sliderControls label[for="slide04"] {
    background: #ddd;
    color: #ddd;
}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
